### ISSUE TITLE
分享歌曲后机器人没有反应

### ISSUE THREAD

**Issue by ShawnQiang1** [kitUIN/nonebot_tools#1]
发送分享歌曲或者分享链接都无应
![QQ截图20210221232821.png](https://i.loli.net/2021/02/21/FbHIx4oauvOmiDz.png)
![QQ图片20210221233044.png](https://i.loli.net/2021/02/21/3piSBuzAr5RPwqm.png)
![QQ截图20210221233105.png](https://i.loli.net/2021/02/21/jcr8HEDditGAao5.png)

**Comment by kitUIN** [comment]
是否启用了解析功能?

**Comment by kitUIN** [comment]
能具体点吗？我无法复现该bug

**Comment by kitUIN** [comment]
或许可以尝试新版本
`pip3 install nonebot-plugin-ncm --upgrade`

**Comment by ShawnQiang1** [comment]
好的我先试试新版本

**Comment by ShawnQiang1** [comment]
作者你这新版本在启动bot,py时又报错了，linux和windows下都报错

**Comment by ShawnQiang1** [comment]
![QQ截图20210302120728.png](https://i.loli.net/2021/03/02/I2qQSrMFRPpJkL4.png)
![QQ截图20210302121120.png](https://i.loli.net/2021/03/02/QtHxNIP4Xw95CsF.png)
![QQ截图20210302121141.png](https://i.loli.net/2021/03/02/yIlh2DMJpLwi1VQ.png)
![QQ截图20210302121151.png](https://i.loli.net/2021/03/02/VMemFAoCTDSKtYR.png)

**Comment by ShawnQiang1** [comment]
![QQ截图20210302130543.png](https://i.loli.net/2021/03/02/CFyZ9k1egIKvD4z.png)
![QQ截图20210302130552.png](https://i.loli.net/2021/03/02/hJmZ9dbnF37Iy1T.png)
![QQ截图20210302130603.png](https://i.loli.net/2021/03/02/mR27xiJc1EN8XDU.png)
![QQ截图20210302130708.png](https://i.loli.net/2021/03/02/ghN71R9DVuEBzUQ.png)
还是不行啊老哥

**Comment by ShawnQiang1** [comment]
已经启用解析功能

**Comment by kitUIN** [comment]
新版本已解决
