### ISSUE TITLE
有一些问题想请教

### ISSUE THREAD

**Issue by XuLin404** [kitUIN/nonebot_tools#4]
我按照步骤整完了，分享链接也没用反应，控制台输出:nonebot | Event will be handled by <Matcher from nonebot-plugin-ncm, type=message, priority=2, temp=False>
07-26 00:36:05 [INFO] nonebot | Matcher <Matcher from nonebot-plugin-ncm, type=message, priority=2, temp=False> running complete
然后就没有了

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/126971389-cde911a9-c05f-470c-8e66-f410c47360ab.png)
多次分享均未有解析？

**Comment by XuLin404** [comment]
是的

**Comment by kitUIN** [comment]
可以尝试一下新版本
