### ISSUE TITLE
谢谢大佬

### ISSUE THREAD

**Issue by takaqiao** [kitUIN/nonebot_tools#7]
非常棒的插件 但是是否能加关键词辨别下载歌曲呢？或者对链接 小程序识别 现在每个信息都会过一遍插件 很多插件就会失效 因为ncm插件永远优先度高于其他插件

**Comment by kitUIN** [comment]
优先级的话直接调源代码即可
下载歌曲都是靠回复机器人消息识别的
而且nb的消息处理会让每个插件都过一遍信息，一般来说不会出现使其他插件失效的情况

**Comment by kitUIN** [comment]
已在ncm 1.0.6版本中添加了[优先度设置](https://github.com/kitUIN/nonebot_tools/tree/master/nonebot_tools/nonebot-plugin-ncm),在.env系列文件中更改

**Comment by takaqiao** [comment]
感谢更新 等下试试还会不会出现这种情况



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kitUIN ***@***.***&gt;
发送时间: 2021年9月24日 18:58
收件人: kitUIN/nonebot_tools ***@***.***&gt;
抄送: takaqiao ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[kitUIN/nonebot_tools] 谢谢大佬 (#7)





 
已在ncm 1.0.6版本中添加了优先度设置,在.env系列文件中更改
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
